### ISSUE TITLE
Preserve CSS Transforms

### ISSUE THREAD

**Issue by jeffzh4ng** [scrollreveal/scrollreveal#251]
Hello!

Is there any way to stop scrollreveal.js from overriding and removing my css property transform: scale(x, y) on image hover? When I remove scrollreveal.js my images scale on hover, but when I add scrollreveal.js back in my css properties get overridden and removed.

**Comment by jlmakes** [comment]
Hey @jeffzhangg 

I’m labeling this as a feature request because this is something I anticipated, but was waiting for community interest in. Presently, ScrollReveal preserves:

- Inline styles
- Opacity
- Transitions

However, Transforms (specifically rotation and scale) are overwritten. Expect to see this addressed in the next release of ScrollReveal (`v3.2.0`).

**Comment by amriterry** [comment]
When will this issue be fixed?

**Comment by jlmakes** [comment]
Well @amriterry, I'm not sure but you can follow along with the [development branch](https://github.com/jlmakes/scrollreveal/tree/development). I'm in the process of splitting the library into testable modules, and all open issues will be addressed before release.

**Comment by jlmakes** [comment]
I've just rediscovered why I didn't support this the first time around @jeffzhangg @amriterry 

The computed style transform is stored as a matrix. For example, `rotateX(45deg)` becomes `matrix3d(1, 0, 0, 0, 0, 0.707107, 0.707107, 0, 0, -0.707107, 0.707107, 0, 0, 0, 0, 1)`. I've had some exposure to representing vectors with a matrix, and I know that `0.707107` is the square root of `0.5`, but I may need a little help on this one.

It appears for this issue to be addressed, I will need to:
- Use matrix transformations under the hood 😰
- Add the existing transform matrix to the generated one 😱

**Comment by jlmakes** [comment]
I've actually got this working... it's combining transformations! 🎉 

### But the solution(s) were already there...

I know I'm months late on this @jeffzhangg, but next time you should actually be able to use `!important` on your `:hover` style to overwrite any inline styles generated by ScrollReveal.

If you wanted to prevent the hover events from interrupting the reveal animation, you could use the ScrollReveal callbacks to add a class with your hover styles (using `!important`) when reveals complete.

**Edit**: I don't know why these are all hitting me NOW... but another solution could be to wrap your elements with transform on hover in a `div`, and reveal _that_ element instead.
