### ISSUE TITLE
Only use transform when it's needed

### ISSUE THREAD

**Issue by chrismilway** [scrollreveal/scrollreveal#292]
Because Chrome renders text poorly when it's inside a transformed element, it might be a good idea to only use CSS transform when the config requires it. For example if i use the following config it shouldn't require transforming:

``` js
var config = {
    viewFactor: 0.15,
    duration: 500,
    distance: '0', // No translate needed
    scale: 1, // No scale needed
    reset: true,
    easing: 'ease-out'
}
```

It would also be nice if the inline style was removed once the animation is complete for the same reason.

**Comment by jlmakes** [comment]
Thanks for sharing your ideas @chrismilway, I agree these would be improvements. I'm working on a quite a few things for ScrollReveal as we enter 2017, including a complete re-write, automated selenium testing across browsers (thanks Browserstack), and brand new web/video documentation.

I'll make sure your suggestions make their way into this upcoming release.
