### ISSUE TITLE
Add class to <html> when ScrollReveal is supported and active

### ISSUE THREAD

**Issue by jlmakes** [scrollreveal/scrollreveal#294]
### Problem

Elements may be rendered by the browser before ScrollReveal's JavaScript has had time to run, which means revealed elements may be visible for a brief moment when the page first loads.
### Now

To ensure revealed elements load hidden, it's recommended to load ScrollReveal at the top of your document alongside the follow code:

``` html
<!-- load and instantiate ScrollReveal first -->
<script src="js/scrollreveal.min.js"></script>
<script>
  window.sr = new ScrollReveal();

  // Add class to <html> if ScrollReveal is supported
  if (sr.isSupported()) {
    document.documentElement.classList.add('sr');
  }
</script>
```

This allows you to use ScrollReveal specific CSS that can apply `visibility: hidden` to your elements on load. For example:

``` html
<div class="foo">Hello world!</div>
```

``` css
.sr .foo { visibility: hidden; }
```
#293 brought to my attention to a _missed opportunity to automate these recommendations_.
### Future

My proposed solution is similar to what's present in the documentation--but ran for you under the hood during instantiation so `.sr` is automatically available on `<html>`.

``` js
// We only care about managing our starting
// visibility style if the library is supported.
if (sr.isSupported()) {
  // However, we also want to make sure that we don't do
  // anything on mobile devices with config.mobile = false.
  if (sr.tools.isMobile() && !sr.defaults.mobile) {
    return
  } 
  // Now we can safely add our hook to manage
  // our element's starting visibility.
  document.documentElement.classList.add('sr');
}
```

**Comment by davdenic** [comment]
i like it
