### ISSUE TITLE
HTML Demo page

### ISSUE THREAD

**Issue by pcoughlin** [scrollreveal/scrollreveal#311]
I am interested in using your excellent scrollreveal module for Drupal.

I noticed that you reference [https://scrollrevealjs.org/ ](https://scrollrevealjs.org/)in the README.md, but the code is not in the Repo.

When I tried the simple "save as" from the browser, it did not work and changed the classes into inline Styles which confuses everything.

It would be great to get the HTML for the home page of ScrollRevealjs.org. If you do not want to make it available, then I understand. It is a great learning example that you created.

Thanks for all the work and everything thus far.

Also, if there is any cleanup work (like making the URL's different for another generic site or any other cleanup work on the page ... then I would be happy to do the work to get it cleaned up (if needed) then post a pull to add it to the repo (or however you want it done). Not intending to ask you for extra work here.

Thanks,
Paul

**Comment by jlmakes** [comment]
Hey Paul,

I think it's a great idea, and it's come up before (#259).
I'm pleased to say this will be addressed very soon!

I'm working on a big release for the new year, including some new features, automated unit tests across browsers, and greatly improved documentation; I will make sure the demo page, along with other examples, are a part of it.

**Comment by hartonos** [comment]
Demo page is unique, but not showing all scrollreveal ability
thx
