### ISSUE TITLE
No effect option

### ISSUE THREAD

**Issue by Alex360hd** [scrollreveal/scrollreveal#337]
Hello,

Very nice plugin, I use it each time I need to add effects on a website and it always does the job !

However, I have a small feature request. It would be great to have an option to disable animation (I mean all inline styles set on element), because sometimes, I use the `options.beforeReveal` callback function to do custom stuff, but I don't need to animate the element.

I was thinking something like this...

```js
sr.reveal('#element', {
  animation: false, // something like this?
  beforeReveal: function (domEl) {
    domEl.classList.add('active');
  }
}, 300);
```

Today, I can do the job by resetting all effects (opacity:1, scale:1, distance:0, etc....) but it still adds all the unnecessary inline style to the element. Being able to completely disable it would be better, allowing users to just use the power of callback functions.

What do you think about it ?

**Comment by jlmakes** [comment]
I think this is a great idea @Alex360hd, thanks for sharing your ideas and support.

**The good news** is that I’ve already been exploring this feature for the new [version 4](https://github.com/jlmakes/scrollreveal/pull/323), and I’m positive this will make its way into the API.

**The bad news** is that I haven’t yet found a good solution, and I'm considering launching version 4 without it—and adding it in later for version 4.1. It’s nice to get some community interest though, so I’ll give it another shot before release.

***

Also, you brought this up:

>Today, I can do the job by resetting all effects (opacity:1, scale:1, distance:0, etc....) but it still adds all the unnecessary inline style to the element

This has been improved in v4, ScrollReveal will no longer create/apply unnecessary styles. So for example, if you use `options.opacity = 1` on an element that already has `opacity: 1`, no opacity styles will be generated.

***

If you’d like, check out [what's different in v4](https://github.com/jlmakes/scrollreveal/blob/development/CHANGELOG.md) and give the beta a try:
```
https://unpkg.com/scrollreveal@4.0.0-beta.3/dist/scrollreveal.min.js
```
It’s already quite stable (and in use on scrollrevealjs.org), but your feedback would be greatly appreciated—just post your thoughts, experiences, bugs, etc. [here](https://github.com/jlmakes/scrollreveal/pull/323).

I’ll make sure to keep you updated on the progress of your feature request.

**Comment by Alex360hd** [comment]
Excellent, I will test this V4 on my next test website.

Thank you for your answer, and continue that great work !

**Comment by jlmakes** [comment]
Here’s an example of how you could monkey patch this feature (using v4):

```js
window.sr = ScrollReveal()

sr.watch = function (target, onEnter, onExit, interval) {
    /**
     * Shuffle things around to support
     * optional onExit argument.
     */
    if (typeof onExit === 'number') {
        interval = onExit
        onExit = function () {}
    } else {
        onExit = onExit || function () {}
        interval = interval || 0
    }

    if (typeof onEnter === 'function' && typeof onExit === 'function') {
        this.reveal(target, {
            delay: 0,
            distance: '0',
            duration: 0,
            easing: 'linear',
            opacity: null,
            origin: 'bottom',
            rotate: {
                x: 0,
                y: 0,
                z: 0,
            },
            scale: 1,
            container: this.defaults.container,
            desktop: this.defaults.desktop,
            mobile: this.defaults.mobile,
            reset: true,
            useDelay: 'always',
            viewFactor: this.defaults.viewFactor,
            viewOffset: this.defaults.viewOffset,
            afterReset () {},
            afterReveal () {},
            beforeReset: onExit,
            beforeReveal: onEnter,
        }, interval)
    } else {
        throw new Error('Watch received invalid arguments.')
    }
}
```

Then it could be used like this with both handlers, but no interval

```js
sr.watch('.items', function (el) {
    el.classList.add('active')
})
```

Or with all the bells and whistles...

```js
sr.watch('.items', function onEnter (el) {
    el.classList.add('active')
}, function onExit (el) {
    el.classList.remove('active')
}, 200)
```
