### ISSUE TITLE
Commercial License for v4

### ISSUE THREAD

**Issue by ekfuhrmann** [scrollreveal/scrollreveal#345]
What's the best way of reaching out to you in regards to pricing/obtaining a commercial license for v4?

**Comment by jlmakes** [comment]
All license information (and checkout) will be available on the new website very soon. In the mean time, you can shoot me an email at julianlloyd@gmail.com and I’d be happy to answer your questions.

**Comment by discoveryjames** [comment]
Are you losing the MIT license?

**Comment by jlmakes** [comment]
@discoveryjames Yes, all versions of ScrollReveal will undergo a license change soon.

_This isn’t final and legally binding copy, but this should give you a good idea:_

#### Open Source

For open source and personal projects, ScrollReveal will be available under the [GPLv3](https://www.gnu.org/licenses/gpl-3.0.html). Releasing projects that use ScrollReveal under the GPLv3, in turn, require those projects to also be licensed under the GPLv3.

#### Commercial 

The commercial license is designed to for you to use ScrollReveal in commercial products and applications, without the provisions of the GPLv3. The commercial license will keep your code proprietary, and allow the use of ScrollReveal to develop commercial sites, themes, projects, and applications.

**Comment by discoveryjames** [comment]
@jlmakes If we want to use ScrollReveal on our client's website, will we need purchase a commercial license? If so, does the licensing consider multi-website use cases?

**Comment by jlmakes** [comment]
Yes, and yes @discoveryjames. More details will be available soon.

**Comment by discoveryjames** [comment]
@jlmakes when are you expecting to launch the commercial license?

I'm still using an older version of the beta, it would be good to be able to buy a license.

**Comment by jlmakes** [comment]
I appreciate the follow-up.

I’m working full-time on v4, mostly on the new website/documentation (over 30 pages of info, with examples). I should be done within the new couple weeks, and I’ll be sure to ping you on Github when that happens!

Also, I push updates to the beta every few days, and `beta.22` is looking _very_ solid; I recommend you upgrade, or better yet, use a self-updating link such as `https://unpkg.com/scrollreveal@beta`

Thanks @discoveryjames

**Comment by discoveryjames** [comment]
No problem - looking forward to it.

I held back on the older versions due to the new betas having a license change but without the ability to purchase a license.

Are we ok to use the beta commercially until the licensing model is launched?

**Comment by jlmakes** [comment]
Yes, you have my permission to use v4 on good faith that you'll purchase a license when it becomes possible.

**Comment by adr-05** [comment]
I develop commercial WordPress themes, will I be able to use v4 in them as long as I purchase the commercial license?
Will v3 remain MIT?

**Comment by jlmakes** [comment]
> I develop commercial WordPress themes, will I be able to use v4 in them as long as I purchase the commercial license?

Yes! There is an extended commercial license for product developers (making themes, plug-ins, interface builders, etc), granting unlimited resale.

> Will v3 remain MIT?

If there are any new releases of v3, they will be under the new GPLv3 + Commercial license. However, these changes will not be retroactive, so if you already possess a MIT licensed version of ScrollReveal, you can still exercise that license.

These changes are to help sustain development and community support _moving forward_.

**Comment by nikoladim123** [comment]
i used ScrollReveal in my commercial app without license...
is that illegal?

**Comment by jlmakes** [comment]
@nikoladim123 If you used ScrollReveal 4, yes commercial use without a license is illegal.

Earlier versions of ScrollReveal remain under the MIT licensed.

**Comment by AysunSachir** [comment]
Hello,

A question just to clarify some aspects for the commercial license.
Me, as a developer, I'm working as an employee at an agency that has website. If I use the plugin when creating the website, do I need to buy a license?

**Comment by jlmakes** [comment]
@AysunSachir Thanks for reaching out! If your employer is comfortable open sourcing their website under the GPLv3 license, they don't need to purchase anything. Otherwise, they should buy a license according to the size of their developer team.

**Comment by AysunSachir** [comment]
@jlmakes Thanks! The website is actually a static version of html/css with a few jquery plugins. Not sure how an organisation would make this open source?

**Comment by jlmakes** [comment]
I understand why you say that, as it's not a product or tool — but it really just means they would make those static files available for download explicitly under the GPLv3 license. This helps others learn, and grants them freedom to use any helpful code snippets employed on the site.

**Comment by AysunSachir** [comment]
Ah ok, now it makes sense. I will talk with them about this.
Thank you for taking the time to reply!
