### ISSUE TITLE
When will ScrollReveal 4 be released?

### ISSUE THREAD

**Issue by Ghost180195** [scrollreveal/scrollreveal#395]
Hello. Thank you for such a wonderful library. I'm looking forward to the new version. When will the release of the new version be?

**Comment by jlmakes** [comment]
Thanks @Ghost180195,

With any luck, I'll be done this month. I really underestimated how much work writing the new documentation would be, but it's almost done and looking great.

**Comment by jlmakes** [comment]
Soon @Alex360hd! The docs are finished, but not yet online while I finish building the license checkout.

I've done what I can to keep almost all of it backwards compatible, so if you're familiar with the current API, I've made sure the `development` branch [changelog](https://github.com/jlmakes/scrollreveal/blob/development/CHANGELOG.md) is accurate and up-to-date.
