### ISSUE TITLE
Firefox Performance

### ISSUE THREAD

**Issue by brentbarkley** [scrollreveal/scrollreveal#449]
OSX
Firefox 61.0.1
ScrollReveal 3.4.0

After adding a relatively simple SR request, the whole page is just jerky/jumpy/sticky when scrolling. SR ultimately works, but the performance is poor. If I remove SR, page performs fine. Note: only in Firefox--other browsers perform well!

Did my homework and didn't find anything helpful through an hour of investigating. Is this a known problem with Firefox or is it likely related to some conflict/code in our site? Can share a link to our dev site privately, but would rather not here. Just looking for a hint of where I might need to look to address a browser-specific performance issue like this.

**Comment by jlmakes** [comment]
Hey Brent,

I haven’t observed stark differences in performance across browsers.

I’m not sure what could be causing the slow downs, but a community member did point out that the `scroll` event listeners are not [passive](https://developers.google.com/web/updates/2016/06/passive-event-listeners) (#416). This could be something to explore on your own, but definitely something that will soon see its way into a future release.

Did you run the browsers performance profiler on your page?
