### ISSUE TITLE
Chrome and Firefox stopped supporting ScrollReveal. My website not working now.

### ISSUE THREAD

**Issue by kindacoder** [scrollreveal/scrollreveal#450]
### Environment

* Operating System:
* Browser Version:
* ScrollReveal Version:

**Comment by jlmakes** [comment]
I'm going to guess that you were not using a fixed version number in production, and so your page has automatically started using ScrollReveal 4 (which launched a few hours ago).

If you were doing something like this:

```html
<script src="https://unpkg.com/scrollreveal"></script>
```

You should specify a fixed version number (and the minified distribution) like this:

```html
<script src="https://unpkg.com/scrollreveal@3.4.0/dist/scrollreveal.min.js"></script>
```
