### ISSUE TITLE
Uncaught TypeError: afterCallback is not a function

### ISSUE THREAD

**Issue by twister65** [scrollreveal/scrollreveal#454]
* Operating System: Windows 10
* Browser Version: Chrome Version 68.0.3440.106
* ScrollReveal Version: 4.0.0

```
Uncaught TypeError: afterCallback is not a function
    at scrollreveal.js:876: 
```
```js
function registerCallbacks(element, isDelayed) {
	var afterCallback = element.revealed
		? element.config.afterReveal
		: element.config.afterReset;
	afterCallback(element.node); // <--???
```

**Comment by jlmakes** [comment]
Can you give more details about how you were using ScrollReveal?

**Comment by jlmakes** [comment]
Can you give more details about how you are using ScrollReveal?

**Comment by twister65** [comment]
https://github.com/twister65/joomspirit_99/blob/sr_v4/joomspirit_99/index.php
line 219 : load and instantiate ScrollReveal.
line 555 : use of ScrollReveal.

**Comment by twister65** [comment]
Sorry, for this issue, I instantiated this library: 
https://github.com/scrollreveal/scrollreveal/blob/master/dist/scrollreveal.js

**Comment by jlmakes** [comment]
My goal @twister65, is to be able to reproduce this issue so I can effectively experiment with solutions. I put together a [basic test](http://jsbin.com/kovubaxico/1/edit?html,console,output), and the callbacks seem fine.

The only way I’ve reproduced this issue is by setting `options.afterReveal` to the wrong type, e.g:

```js
ScrollReveal().reveal('.item', {
    afterReveal: {}
});

// => TypeError: afterCallback is not a function
```

I notice you’re passing the options using PHP, i.e:

```php
sr.reveal('.social-links', { <?php echo $this->params->get('animation_social_text'); ?> });
```

My guess would be that something isn’t quite right in the value returned from PHP. I would double check what `$this->params->get('animation_social_text');` (and other similar expressions) are returning.

**Comment by twister65** [comment]
I don't understand code line 876 in scrollreveal.js. Is afterCallback a function or a variable ?

**Comment by jlmakes** [comment]
`afterCallback` is indeed a variable, that points to one of two functions.

Do you mind posting the output from `$this->params->get('animation_social_text');` for example?

**Comment by twister65** [comment]
Output from : sr.reveal('.text_social_icons', { <?php echo $this->params->get('animation_social_text'); ?>, afterReset:baffleSelection('.text_social_icons') });
<span class="text_social_icons hidden-phone" style="color:#555555; visibility: visible; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transition: opacity 1.33s cubic-bezier(0.5, 0, 0, 1) 0s, transform 1.33s cubic-bezier(0.5, 0, 0, 1) 0s;" data-sr-id="2">Suivez moi : </span>

**Comment by twister65** [comment]
`<span class="text_social_icons hidden-phone" style="color:#555555; visibility: visible; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transition: opacity 1.33s cubic-bezier(0.5, 0, 0, 1) 0s, transform 1.33s cubic-bezier(0.5, 0, 0, 1) 0s;" data-sr-id="2">Suivez moi : </span>`

**Comment by jlmakes** [comment]
Alors Nicolas, je peux essayer en français pour toi.

Je pense que le problème est le résultat du code PHP, pas du ScrollReveal. Quand tu as une ligne comme celui-ci:

```php
$this->params->get('animation_social_text');
```

PHP le remplacera avec du texte no? Je devinerai un transformation en objet JavaScript, par exemple:

```js
{ duration: 1300 }
```

Pouvez-vous mettre le vrai transformation pour moi? Je crois que ce chemin montrera le valeur incorrect avec `options.afterReveal` tu vois?

**Comment by jlmakes** [comment]
Alors Nicolas, je peux essayer en français pour toi.

Je pense que le problème est le résultat du code PHP, pas du ScrollReveal. Quand tu as une ligne comme celui-ci:

```php
$this->params->get('animation_social_text');
```

PHP le remplacera avec du texte non? Je devinerai un transformation en objet JavaScript, par exemple:

```js
{ duration: 1300 }
```

Pouvez-vous mettre le vrai transformation pour moi? Je crois que ce chemin montrera le valeur incorrect avec `options.afterReveal` tu vois?

**Comment by twister65** [comment]
Sorry, I reinstalled the template with ScrollReveal and the error is gone. I don't understand why. You can close this issue.

**Comment by twister65** [comment]
origin:'top', distance:'20px', duration:1330, reset:true

afterReset raises this error after scrolling back the window.
`afterReset:baffleSelection('.text_social_icons')`

**Comment by jlmakes** [comment]
seems like `baffleSelection('.text_social_icons')` is not a function.

**Comment by twister65** [comment]
`function baffleSelection($e) {
				let b = baffle($e);
				b.start()
					.set({ speed: 40 })
					.reveal(3000,1500);
			}`

**Comment by jlmakes** [comment]
You are invoking the function `baffleSelection()` instead of assigning it. That means the return value will be used for `options.afterReset`instead of the function itself.

Donc pas comme ceci:

```js
sr.reveal('.text_social_icons', {
  <?php echo $this->params->get('animation_social_text'); ?>, 
  afterReset: baffleSelection('.text_social_icons')
});
```

Fait cela:

```js
sr.reveal('.text_social_icons', {
  <?php echo $this->params->get('animation_social_text'); ?>, 
  afterReset: function() {
    baffleSelection('.text_social_icons');
  }
});
```
