### ISSUE TITLE
Sync restting all items on page after ajax

### ISSUE THREAD

**Issue by CHEWX** [scrollreveal/scrollreveal#457]
Hi,

When using `ScrollReveal().sync();` on ajax callback, it seems to be resetting all items on the page, not the new items.

Cannot find any information on this.

Thanks

**Comment by CHEWX** [comment]
I've hacked a fix like this for now, but should be doing something similar as default.

`afterReveal: (el)  => $(el).removeAttr('data-sr')`

**Comment by jlmakes** [comment]
Hey @CHEWX 

When opening issues (for any repository), it’s helpful to include the operating system, library version and example code.

ScrollReveal 4 uses the `data-sr-id` attribute to link HTML elements to their animation data stored within ScrollReveal. **Don’t remove this manually**, as it won’t remove event listeners or store data. If you need to remove ScrollReveal from specific elements you should use [`clean()`](https://scrollrevealjs.org/api/cleanup.html).

Without more information, I can only guess that your problem is related to [`options.cleanup`](https://scrollrevealjs.org/api/cleanup.html)

**Comment by jlmakes** [comment]
Hey @CHEWX 

When opening issues, it’s helpful (for me, and future visitors) to include the operating system, library version and example code—ideally as a working demo. 

Based on my understanding of your problem, I recommend reading the docs on [`options.cleanup`](https://scrollrevealjs.org/api/cleanup.html)

**Comment by jlmakes** [comment]
Also, `data-sr` looks like a typo in your example callback.

ScrollReveal 4 uses the `data-sr-id` attribute to link HTML elements to their animation data stored within ScrollReveal. **Don’t remove this manually**, as it won’t remove event listeners or store data. If you need to remove ScrollReveal from specific elements you should use [`clean()`](https://scrollrevealjs.org/api/clean.html).

**Comment by jlmakes** [comment]
Hey @CHEWX 

Based on my understanding of your problem, I recommend reading the docs on [`options.cleanup`](https://scrollrevealjs.org/api/cleanup.html)

Also, `data-sr` looks like a typo in your example callback.

ScrollReveal 4 uses the `data-sr-id` attribute to link HTML elements to their animation data stored within ScrollReveal. **Don’t remove this manually**, as it won’t remove event listeners or store data. If you need to remove ScrollReveal from specific elements you should use [`clean()`](https://scrollrevealjs.org/api/clean.html).

**Comment by jlmakes** [comment]
Any luck @CHEWX ?

**Comment by jlmakes** [comment]
Hey, I'm suspicious this may be a bug.

It looks like you are using `[data-sr]` as your reveal target, e.g.
```js
ScrollReveal().reveal('[data-sr]');
```

And you’re removing the attribute after the reveal completes, so they don’t re-reveal when you call `sync()` in your AJAX callback. When you set [`options.cleanup`](https://scrollrevealjs.org/api/cleanup.html) to `false` does it work correctly?

**Comment by jlmakes** [comment]
Hey @CHEWX  I'm suspicious this may be a bug. Thanks for the issue.

I’m guessing you are using `[data-sr]` as your reveal target, e.g.
```js
ScrollReveal().reveal('[data-sr]');
```

And you’re removing the attribute after the reveal completes, so they don’t re-reveal when you call `sync()` in your AJAX callback.

Do me a favor, when you set [`options.cleanup`](https://scrollrevealjs.org/api/cleanup.html) to `false` does it work correctly?

**Comment by jlmakes** [comment]
Hey @CHEWX, thanks for the issue. I'm suspicious this may be a bug.
Do me a favor, when you set [`options.cleanup`](https://scrollrevealjs.org/api/cleanup.html) to `false` does it work correctly?

**Comment by CHEWX** [comment]
Hi @jlmakes 

I appreciate your replies!

I'm away at the moment, but happy to test on my return.

My current setup is the following to avoid any assumptions.

```
    scrollreveal : {

        init () {

            this.vars();

            this.setup();

        },

        vars () {

            this.sr = ScrollReveal();
            this.options = {
                delay: 250,
                distance: '50px',
                duration: 1250,
                easing: 'cubic-bezier(0.15, .35, 0, 1)',
                mobile: true,
                afterReveal: (el)  => $(el).removeAttr('data-sr')
            }

            if( Foundation.MediaQuery.atLeast('xlarge') ) {
                this.options.container = '.site-scroll';
            }

        },

        setup () {

            this.sr.reveal('[data-sr]', this.options);


        }

    },
```

**Comment by jlmakes** [comment]
No problem! I’ve recreated the bug on [JSbin](jsbin.com/bejubivaya/edit?html,output).
