### ISSUE TITLE
ScrollReveal doesn't work at scroll

### ISSUE THREAD

**Issue by wizardnet972** [scrollreveal/scrollreveal#458]
ScrollReveal doesn't work with `transform: translate3d`. 

Here is example:
https://codepen.io/shlomilevi/pen/aajPNg

**Comment by wizardnet972** [comment]
Sorry. I remove the wrap from the css and it is working.

**Comment by jlmakes** [comment]
Opening up the inspector on the [3rd party demo](https://idiotwu.github.io/smooth-scrollbar/), I discovered it uses CSS Transforms (i.e. `translate3D`) to create the "smooth" scrolling effect. ScrollReveal relies on _native scroll events_, but none are firing from your Smooth Scrollbar container.

The  [`smooth-scrollbar`](https://cdnjs.cloudflare.com/ajax/libs/smooth-scrollbar/8.3.1/smooth-scrollbar.js) plug-in you are using does not appear to be compatible with ScrollReveal.

**Comment by dinh-tu-fool** [comment]
Any alternative solution to implement both of these?

**Comment by jlmakes** [comment]
@dinh-tu-fool ScrollReveal uses `scroll` (and `resize`) events to trigger calls to `ScrollReveal().delegate()` which is the main event handler that checks element dimensions, visibility, etc. However, there's no reason you can't call `delegate` when and however you want.

So if your smooth scrolling library doesn't use `scroll` events, it's up to you to call `ScrollReveal().delegate()` in response to some other event triggered by your smooth scrolling implementation.

**Comment by jlmakes** [comment]
@dinh-tu-fool ScrollReveal 4 uses `scroll` (and `resize`) events to trigger calls to `ScrollReveal().delegate()` which is the main event handler that checks element dimensions, visibility, etc. However, there's no reason you can't call `delegate` when and however you want.

So if your smooth scrolling library doesn't use `scroll` events, it's up to you to call `ScrollReveal().delegate()` in response to some other event triggered by your smooth scrolling implementation.

**Comment by jlmakes** [comment]
@dinh-tu-fool ScrollReveal 4 uses `scroll` (and `resize`) events to trigger calls to `ScrollReveal().delegate()` which is the main event handler that checks element dimensions, visibility, etc. However, there's no reason you can't call `delegate` when and however you want.

So if your smooth scrolling library doesn't use `scroll` events, it's up to you to call `ScrollReveal().delegate()` in response to some other event triggered by your smooth scrolling implementation. And of course, make sure to set the right [`options.container`](https://scrollrevealjs.org/api/container.html) if you're getting fancy.

**Comment by haroldao** [comment]
> @dinh-tu-fool ScrollReveal 4 uses `scroll` (and `resize`) events to trigger calls to `ScrollReveal().delegate()` which is the main event handler that checks element dimensions, visibility, etc. However, there's no reason you can't call `delegate` when and however you want.
> 
> So if your smooth scrolling library doesn't use `scroll` events, it's up to you to call `ScrollReveal().delegate()` in response to some other event triggered by your smooth scrolling implementation. And of course, make sure to set the right [`options.container`](https://scrollrevealjs.org/api/container.html) if you're getting fancy.

delegate ?
