### ISSUE TITLE
First page load animation 

### ISSUE THREAD

**Issue by bonucci** [scrollreveal/scrollreveal#461]
Hello, im having a issue on the page, basically i have a one html page with some sections that includes slider, texts and some images, the problem is that when i load the page, in a glamps the page is scrolled down but then scrolls up automatclly, the problem in these miliseconds the anination from scrollreveal fires first time, loossing my animation on the scroll.

Is someone had same situation?

### Environment

* Windows 10
* Chrome 69.0.3497.100 
* ScrollReveal Version: 4.0.4

**Comment by JohnPhilosopher** [comment]
Are you aware of any code that could be causing the automatic scroll-up besides scroll reveal? Scroll reveal seems to be working in that regard as when the elements are in view they are revealed. I have not had any issues with scroll reveal causing the page to automatically scroll up to the top of the page, though this is with older versions.

**Comment by jlmakes** [comment]
One thing that comes to mind is that large images can cause dramatic shifts in layout while the page loads. Maybe that's helpful?

In any case, ScrollReveal does not ever change your scroll position.

**Comment by jlmakes** [comment]
ScrollReveal does not ever change your scroll position. One thing that comes to mind is that large images can cause dramatic shifts in layout while the page loads. Maybe something similar is happening for you.

**Comment by jlmakes** [comment]
ScrollReveal does not ever change your scroll position. One thing that comes to mind is that large images can cause shifts in layout while the page loads. Maybe something similar is happening for you.
