### ISSUE TITLE
Origin Reveal Option doesn't works?

### ISSUE THREAD

**Issue by D4RKAR117** [scrollreveal/scrollreveal#463]
### Environment

* Operating System: Windows 10 pro x64 v 1803
* Browser Version: Opera v55.0.2994.61
* ScrollReveal Version: release 4.0.4 using cdn

Hello, after a while I come back with another issue, I'm trying to display a [page](https://d4rkar117.github.io/stalker-bot/) on github pages using your amazing script, it works to a certain extent, the problem is that [the "origin" option](https://scrollrevealjs.org/api/origin.html) does not apply the effects it should, possibly I'm doing something wrong but I've tried several times with different options like local scripts, changing styles and events, but it does not work, another minor thing is that by following [your recommendations to avoid flickering](https://scrollrevealjs.org/guide/user-experience.html) in the load of the page if the css visibility option is hidden it is added !important like `visibility: hidden !important;` will not work the reveal, it is something uncomfortable sometimes, attached screenshots the my javascript script

This is the file that executes the reveals, **the commented options disable them to verify that they were not the cause of the problem**, but it does not matter if they are active or inactive

![image](https://user-images.githubusercontent.com/23545823/46335222-61e2b000-c5ec-11e8-87bc-0338d8b0545b.png)

This other screenshot shows the structure of my index.html file, **I use all the scripts in the head section**
![image](https://user-images.githubusercontent.com/23545823/46335342-b8e88500-c5ec-11e8-972a-0bee5a9b6edf.png)

And this one **is the CSS styles file that I use with the recommendations of your script and without the property: !Important**
![image](https://user-images.githubusercontent.com/23545823/46335448-209ed000-c5ed-11e8-9d2e-4fbfe62aa875.png)

Even if you want to verify the files yourself you can check the docs folder of [my repository](https://github.com/D4RKAR117/stalker-bot), which is published in the github pages

Keep up the good work friend, I have made this script one of the essential elements when creating web pages.

**Comment by jlmakes** [comment]
Thanks for the kind words.

There is nothing wrong with [`options.origin`](https://scrollrevealjs.org/api/origin.html) in [my test](https://jsbin.com/kazimikati/1/edit?html,output); as noted in the docs:

> You will need a non-zero value assigned to [`options.distance`](https://scrollrevealjs.org/api/distance.html) for [`options.origin`](https://scrollrevealjs.org/api/origin.html) to have any visible impact on your animations.

**Comment by D4RKAR117** [comment]
ooohhh deam sorry man i feel a idiot right now

**Comment by jlmakes** [comment]
It's no problem, sometimes the issue is just one missing `;` that's how it goes.

Also your `visibility: hidden` code is missing the `html.sr` hook for all of your classes; you have this:

```css
html.sr .top-reveal, .bot-reveal, .right-reveal, .left-reveal {
  visibility: hidden;
}
```

But you'd want something like this:
```css
html.sr .top-reveal,
html.sr .bot-reveal,
html.sr .right-reveal,
html.sr .left-reveal {
  visibility: hidden;
}
```

Make sure to include the `html.sr` hook in them all.

**Comment by D4RKAR117** [comment]
Oh thank you I had not noticed, and about the attribute: !Important, you think it's something important? sometimes some classes do not allow you to apply the hidden cuz it override the principal

**Comment by jlmakes** [comment]
I'm not sure I understand, where is the `!important` coming from?

**Comment by D4RKAR117** [comment]
I refer to this friend 
```css
html.sr .top-reveal,
html.sr .bot-reveal,
html.sr .right-reveal,
html.sr .left-reveal {
  visibility: hidden !important;
}
```

Whenever this attribute is important in the hidden, the animations will never start, and it is uncomfortable because sometimes the hidden is overwritten by another style

**Comment by jlmakes** [comment]
I understand.

ScrollReveal doesn't use `!important` when it applies `visibility: visible` during animation, so if you use `!important` in your `html.sr` style, _it overrides ScrollReveal_. (No animations can be seen.)

If you'd like, you can make ScrollReveal use `!important` by adding it in your source here:

https://github.com/scrollreveal/scrollreveal/blob/master/dist/scrollreveal.js#L620-L622

**Comment by jlmakes** [comment]
I understand.

ScrollReveal doesn't use `!important` when it applies `visibility: visible` during animation, so if you use `!important` in your `html.sr` style, _it overrides ScrollReveal_. (No animations can be seen.)

If you'd like, you can make ScrollReveal use `!important` by adding it in your source here:

https://github.com/scrollreveal/scrollreveal/blob/master/dist/scrollreveal.js#L620-622

**Comment by jlmakes** [comment]
I understand.

ScrollReveal doesn't use `!important` when it applies `visibility: visible` during animation, so if you use `!important` in your `html.sr` style, _it overrides ScrollReveal_. (No animations can be seen.)

If you'd like, you can make ScrollReveal use `!important` by adding it in your source here:

https://github.com/scrollreveal/scrollreveal/blob/master/dist/scrollreveal.js#L620-L622

**Comment by D4RKAR117** [comment]
Great friend, I will use it, and I would like to request something, options that change depending on the size of the viewport, sometimes some effects are better in mobile than in PC and vice versa, something like the brekpoints but for your script.

Keep up the good work, porcieto
out of the subject thanks for the terminal zsh spaceship now my terminal looks great

**Comment by jlmakes** [comment]
ScrollReveal doesn't support media queries, but it does offer [options.desktop](https://scrollrevealjs.org/api/desktop.html) and [options.mobile](https://scrollrevealjs.org/api/mobile.html). It’s based on the browser's user agent string, but it will let you create unique experiences for both, e.g:

```js
// .items on mobile...
ScrollReveal().reveal('.items', {
  mobile: true,
  desktop: false,
  
  duration: 250,
  scale: 0.9
});

// .items on desktop...
ScrollReveal().reveal('.items', {
  mobile: false,
  desktop: true,
  
  duration: 400,
  scale: 0.8,
  reset: true
});
```

**Comment by D4RKAR117** [comment]
If in fact if I have used them but I think it would be even better to have more flexibility with that kind of options, it would offer even more personalization, but even so it is very cool ;), thanks and sorry for the inconvenience

**Comment by jlmakes** [comment]
No problem, happy coding!
