### ISSUE TITLE
Multiple options

### ISSUE THREAD

**Issue by AndrewDawnbringer** [scrollreveal/scrollreveal#465]
Hello there!
How to pass multiple options to the constructor, like `delay` and `origin` at the same time?
I want to merge `ScrollReveal().reveal('.yourclass', { delay: 500 });` and `ScrollReveal().reveal('.yourclass', { origin: 'left' });`. Thanks in advance.

**Comment by jlmakes** [comment]
These are functionally equivalent:

```js
ScrollReveal().reveal('.yourclass', { delay: 500 });
ScrollReveal().reveal('.yourclass', { origin: 'left' });
```

```js
ScrollReveal().reveal('.yourclass', {
  delay: 500,
  origin: 'left'
});
```

Is that the answer you're looking for @AndrewDawnbringer?

**Comment by AndrewDawnbringer** [comment]
Thank you!
