### ISSUE TITLE
Event for Unrevealed

### ISSUE THREAD

**Issue by Ace000001** [scrollreveal/scrollreveal#466]
Hi! 

I am trying to hook an event (something like beforeUnreveal() and afterUnreveal()) when an elements gets hidden when it is out of view port. In the API i found 4 events but but my impression of those is that  those are when element is showing after coming into view port. Is there any way to do what i am trying to achieve?

Thanks!

**Comment by jlmakes** [comment]
[`option.beforeReset`](https://scrollrevealjs.org/api/before-reset.html) fires after an element leaves the viewport
[`option.afterReset`](https://scrollrevealjs.org/api/after-reset.html) fires after an element leaves the viewport _and_ completes its animation
