### ISSUE TITLE
MIT Licensed alternatives

### ISSUE THREAD

**Issue by iorrah** [scrollreveal/scrollreveal#469]
Hey, I find the work that you folks are doing here super cool. My team and I are interested in using it in a commercial case but we can not afford purchasing the license (startup life!). Are there alternative projects (living under a MIT Licence) to ScrollReveal that people here would suggest for this situation? Thanks a lot in advance & keep rockin'!

**Comment by jlmakes** [comment]
ScrollReveal 3 will always be MIT licensed (see [legacy docs](https://github.com/scrollreveal/scrollreveal/wiki))
