### ISSUE TITLE
How to use Third Party Plugins 

### ISSUE THREAD

**Issue by riiccardo** [scrollreveal/scrollreveal#470]
Hi, Thanks For your Great Plugin 😍 

How To Use Plugins Like:

`1. GreenSock`
`2. Anime.js`
`3. Velocity.js`

In Scrollreveal Plugin

Please Provid An Example For Each Third Party Plugins In The DOC Thanks 🔥 

How To `Remove` ScrollReveal Animation `capabilities`? Like
`opacity, scale, easing, delay, duration`

and just use ScrollReveal for Detecting when elements are visible within the viewport 

Because we want to use `animation tools`, 
and the tools have this features

Regards Sadegh  😄 👍

**Comment by riiccardo** [comment]
any Solution ?

**Comment by jlmakes** [comment]
There are no examples of integrating with those third parties.
You’ll have to read the docs for each, and wire them up yourself 😉

However, a significant portion of ScrollReveal (the code base) is the creation and management of animation styles. If you're only interested in knowing what elements are within the viewport, ScrollReveal may not be a good choice. Maybe take a look at using [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API).

**Comment by riiccardo** [comment]
Thanks For Answer but I Knew it Must Read Doc for These Plugins to understand how to use It,

But How To integrating them with ScrollReveal CallBack #353 ?

U said :

> However, ScrollReveal does provide callback functions for you to easily execute custom JavaScript when elements enter/leave the viewport... so if you needed to "choreograph" animations, or animate values not supported by ScrollReveal, you could call Velocity.js methods inside these callbacks.

**Comment by jlmakes** [comment]
These are ScrollReveal's callbacks:

* [options.afterReveal](https://scrollrevealjs.org/api/after-reveal.html)
* [options.afterReset](https://scrollrevealjs.org/api/after-reset.html)
* [options.beforeReveal](https://scrollrevealjs.org/api/before-reveal.html)
* [options.beforeReset](https://scrollrevealjs.org/api/before-reset.html)

You may also be interested in #394
