### ISSUE TITLE
Cleanup default seems to be false

### ISSUE THREAD

**Issue by bokub** [scrollreveal/scrollreveal#482]
According to [this page of documentation](https://scrollrevealjs.org/api/defaults.html), the default for `cleanup` is `true`

![image](https://user-images.githubusercontent.com/17952318/50541787-3d777f00-0bad-11e9-9f61-e49206773134.png)

However, [**this jsFiddle**](https://jsfiddle.net/bokub/duv06kgr/) proves the opposite:

```js
ScrollReveal().reveal('.a', {}); // Doesn't clean
ScrollReveal().reveal('.b', {cleanup: true}); // Cleans as expected
```

I'm using the latest version from `unpkg.com`

**Comment by jlmakes** [comment]
Thanks for this @bokub.

The documentation there is incorrect: `options.cleanup` defaulting to `true` breaks the expected behavior of the `sync()` method, which was a mistake made during the beta. I have corrected the error!
