### ISSUE TITLE
GNU GPL Question

### ISSUE THREAD

**Issue by devMoxie** [scrollreveal/scrollreveal#484]
I've always been confused with this license so here's my question. I'm developing a single page business landing site. Is this considered commercial use? If not, does the site's code need to be "open soureced?"

**Comment by jlmakes** [comment]
For personal use, regardless of the context (student project, starting a business, teaching, etc.), you may use ScrollReveal 4 under the GPLv3—which requires that your project also be open source under the GPLv3.

Loosely speaking, you would purchase a commercial license if you:

A) would like your source code to be private, or
B) are being paid to build a site using ScrollReveal, or
C) would like to re-sell a digital product (WordPress theme, UI builder, etc.) using ScrollReveal

If you would like, I can send you a sample license for you review the actual legally binding copy: just send an email to service@scrollrevealjs.org

**Comment by jlmakes** [comment]
I also just want to add that purchasing a ScrollReveal 4 license is a one-time act that supports on-going customer support, feature development, bug fixes and performance enhancements.

I understand not everyone has equal purchasing power, and if the license fee is prohibitive, you can  use ScrollReveal 3 (and earlier versions) any way you'd like: they are MIT licensed!

Happy 2019! 🎉

**Comment by Ni-c0de-mus** [comment]
Thanks for that....I'm just learning atm so probably not going to be able
to use it that well atm but if in the future it becomes a reality then
happy days!!!

Kind regards

Nic

**Comment by cokaps016** [comment]
Excuse me, @jlmakes. Can I use this plug in my [MIT license public repo](https://github.com/cokaps016/eleventy-kickstart-blog). This is an open-sourced project (a template for people using 11ty and tailwind css). I will add this to acknowledge section in readme.me after installing ScrollReveal.

**Comment by jlmakes** [comment]
@cokaps016 No, the GPL3 license requires that open source consumers make their project GPL3 as well.

As I mentioned above, if you're willing to use an unsupported version in your project, ScrollReveal 3 remains MIT licensed and free to use. (The documentation for which can be found in the [Wiki](https://github.com/jlmakes/scrollreveal/wiki).)
