### ISSUE TITLE
Stagger animations?

### ISSUE THREAD

**Issue by MariuzM** [scrollreveal/scrollreveal#494]
I have multiple `h1` does ScrollReveal have stagger mode similar to how AnimeJS does it? Reading doc and google nothing really comes up :( 

```html
<div>
	<h1>1</h1>
	<h1>2</h1>
	<h1>3</h1>
	<h1>4</h1>
	<h1>5</h1>
</div>
```

For AnimeJS i would use this `delay: anime.stagger(300)` but i cant use AnimeJS because i want the animation to start when on scroll hence why using ScrollReveal. Maybe way to combine ScrollReveal with AnimeJS?

**Comment by jlmakes** [comment]
Hey @MariuzM, try `options.interval`!

```js
ScrollReveal().reveal('h1', { interval: 300 });
```
