### ISSUE TITLE
Interval (sequential) animation is not working correctly, first item is skipped

### ISSUE THREAD

**Issue by andyduo** [scrollreveal/scrollreveal#497]
Having an issue where an interval animation is not working correctly. The annoying thing is it was working fine all day then suddenly the first image in the sequence started appearing without the reveal so it's visible immediately (all objects are within the browser window on load). Here is my sequence:

```js
ScrollReveal().reveal('.homeLink, .homeImage', {
  interval: 400,
  delay: 1500,
  origin: 'bottom',
  distance: '50px' 
});
```

So the first item no longer slides up 50px or is delayed by 1500. I thought maybe it was because the first item was an image so I changed to just reveal the links and that worked for a while but then the links started doing the same thing.

Any ideas what this could be?

* Windows 10
* Chrome 74.0.3729.157
* ScrollReveal 4.0.5

**Comment by jlmakes** [comment]
@andyduo If it _was_ working and spontaneously stopped, I'm not sure how to help. In the past, caching and script execution order has contributed to hard-to-pin-down issues like this... but nothing comes to mind.

If you reproduce the unwanted behavior (JSBin, Codepen, etc.), I will take a closer look.

**Comment by jlmakes** [comment]
@andyduo If it _was_ working and spontaneously stopped, I'm not sure how to help. In the past, caching and script execution order has contributed to hard-to-pin-down issues like this... but nothing comes to mind. If you reproduce the unwanted behavior (JSBin, Codepen, etc.), I will take a closer look.

**Comment by pShalenniy** [comment]
I got the same problem, fixed with setTimeout
