### ISSUE TITLE
Where Do I Read if This Package Lazy Loads Components

### ISSUE THREAD

**Issue by GaddMaster** [scrollreveal/scrollreveal#508]
Does it actually load everything but simple hides?

I wondering as trying to lazy load components for faster page load speeds?

Daniel

**Comment by jlmakes** [comment]
Using ScrollReveal to animate elements (as their visibility changes) does not alter how those elements load. If you'd like to lazy load images you're revealing, it's up to you to implement that — and either [`reveal`](https://scrollrevealjs.org/api/reveal.html) or [`sync`](https://scrollrevealjs.org/api/sync.html) in a callback for ScrollReveal.
